### ISSUE TITLE
Test coverage is lacking. More tests need to be written.

### ISSUE THREAD

**Issue by hangtwenty** [hangtwenty/cheater-ade#1]
Only the lower-level functionality is currently tested, and more tests need to be written. 

There are issues trying to get Vows to work as expected. It is not clear exactly where the problem lies, but it seems like it's at the collision of my code, Vows, and the YAML library (js-yaml, I think). Basically there's an issue with asynchronous-ness and callbacks and so on, that is causing a certain test to fail.

There's a fork in the road with two possible courses of action:
* Make the script be synchronous since after all it's just a script, and the callback chain is linear and singular anyways
* Don't do that (it would impede speed if this winds up being web-app-ified) - and instead switch test runners, and/or seek help on the issue

**Comment by elisaann** [comment]
Thanks

**Comment by hangtwenty** [comment]
Library is deprecated and unmaintained, I will not fix this
